# Generated by Django 4.2.16 on 2025-02-17 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webapp", "0004_alter_courseenrollments_enrollment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("notif_id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.CharField(max_length=500)),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("forum", "Forum"),
                            ("materials", "Materials"),
                            ("enrollment", "Enrollment"),
                            ("qna", "QnA"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
