# Generated by Django 4.2.16 on 2025-02-17 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webapp", "0007_assignment_uploadassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                ("upload_id", models.AutoField(primary_key=True, serialize=False)),
                ("upload_file", models.FileField(upload_to="uploaded_assignments/")),
            ],
        ),
        migrations.CreateModel(
            name="AssignmentUpload",
            fields=[
                ("assign_id", models.AutoField(primary_key=True, serialize=False)),
                ("upload_file", models.FileField(null=True, upload_to="assignments/")),
                ("deadline", models.DateTimeField(null=True)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.coursedetails",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="uploadassignment",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="uploadassignment",
            name="student",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="UploadAssignment",
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.assignmentupload",
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
