# Generated by Django 4.2.16 on 2025-02-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_assignmentsubmission_assignmentupload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentupload",
            name="description",
            field=models.TextField(default="hello"),
            preserve_default=False,
        ),
    ]
