# Generated by Django 4.2.16 on 2025-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_assignmentupload_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentupload",
            name="name",
            field=models.CharField(default="hello", max_length=255),
            preserve_default=False,
        ),
    ]
