# Generated by Django 4.2.16 on 2025-02-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_assignmentupload_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="status_upadate",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
