# Generated by Django 4.2.16 on 2025-02-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "webapp",
            "0012_remove_userinfo_status_upadate_userinfo_display_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
