# Generated by Django 4.2.16 on 2025-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0013_alter_userinfo_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedetails",
            name="course_header_picture",
            field=models.FileField(null=True, upload_to="profile/"),
        ),
    ]
