# Generated by Django 4.2.16 on 2025-02-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0014_coursedetails_course_header_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursedetails",
            name="course_header_picture",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="profile_picture",
            field=models.FileField(null=True, upload_to="profile/"),
        ),
    ]
