# Generated by Django 4.2.16 on 2025-02-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0015_remove_coursedetails_course_header_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to="profile/"),
        ),
    ]
