# Generated by Django 4.2.16 on 2025-02-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0017_feedbackforum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseenrollments",
            name="enrollment_status",
            field=models.CharField(
                choices=[
                    ("enrolled", "Enrolled"),
                    ("unenrolled", "Unenrolled"),
                    ("removed", "Removed"),
                ],
                default="not_enrolled",
                max_length=20,
            ),
        ),
    ]
