# Generated by Django 4.2.16 on 2025-02-18 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0019_alter_courseenrollments_enrollment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonDetails",
            fields=[
                ("lesson_id", models.AutoField(primary_key=True, serialize=False)),
                ("lesson_title", models.CharField(max_length=255)),
                ("lesson_description", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.coursedetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialUpload",
            fields=[
                ("material_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("upload_file", models.FileField(null=True, upload_to="materials/")),
                (
                    "lesson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.lessondetails",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignmentupload",
            name="lesson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.lessondetails",
            ),
        ),
    ]
