# Generated by Django 4.2.16 on 2025-02-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0021_alter_assignmentupload_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentupload",
            name="description",
            field=models.TextField(default="Refer to attached file.", null=True),
        ),
    ]
