# Generated by Django 4.2.16 on 2025-02-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0023_assignmentsubmission_submitted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile/default.png",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
