# Generated by Django 4.2.16 on 2025-02-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0024_alter_userinfo_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="firstName",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="lastName",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="middleName",
            new_name="middle_name",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="updatedAt",
            new_name="updated_on",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="userType",
            new_name="user_type",
        ),
    ]
