# Generated by Django 4.2.16 on 2025-02-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0026_coursedetails_course_header_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedetails",
            name="course_thumbnail_picture",
            field=models.ImageField(
                blank=True,
                default="course_pictures/thumbnail/default.jpg",
                null=True,
                upload_to="course_pictures/thumbnail",
            ),
        ),
    ]
