# Generated by Django 4.2.16 on 2025-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0027_alter_coursedetails_course_thumbnail_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedetails",
            name="course_header_picture",
            field=models.ImageField(
                blank=True,
                default="course_pictures/header/default.jpg",
                null=True,
                upload_to="course_pictures/header",
            ),
        ),
    ]
