# Generated by Django 4.2.16 on 2025-02-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0028_alter_coursedetails_course_header_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessondetails",
            name="course",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.coursedetails",
            ),
            preserve_default=False,
        ),
    ]
