# Generated by Django 4.2.16 on 2025-02-18 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0029_alter_lessondetails_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentupload",
            name="teacher",
        ),
        migrations.AddField(
            model_name="coursedetails",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lessondetails",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lessondetails",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="materialupload",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materialupload",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
