# Generated by Django 4.2.16 on 2025-02-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0030_remove_assignmentupload_teacher_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Table",
        ),
    ]
