# Generated by Django 4.2.16 on 2025-02-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0031_delete_course_delete_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentupload",
            name="course",
        ),
    ]
