# Generated by Django 4.2.16 on 2025-02-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0032_remove_assignmentupload_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="submitted_at",
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="submission_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="submitted_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="upload_file",
            field=models.FileField(
                default="uploaded_assignments/default.jpg",
                upload_to="uploaded_assignments/",
            ),
        ),
    ]
