# Generated by Django 4.2.16 on 2025-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0034_assignmentupload_assignment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("overdue", "Overdue"),
                    ("due", "Due"),
                ],
                default="due",
                max_length=20,
            ),
        ),
    ]
