# Generated by Django 4.2.16 on 2025-02-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0037_meetingdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingdetails",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_details",
                to="webapp.requestmeeting",
            ),
        ),
    ]
