# Generated by Django 4.2.16 on 2025-02-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0038_alter_meetingdetails_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingdetails",
            name="duration",
        ),
        migrations.AddField(
            model_name="meetingdetails",
            name="duration_minutes",
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
