# Generated by Django 4.2.16 on 2025-02-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0039_remove_meetingdetails_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
