# Generated by Django 4.2.16 on 2025-02-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0040_alter_userinfo_middle_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
