# Generated by Django 4.2.16 on 2025-02-27 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0041_alter_userinfo_middle_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackforum",
            name="parent_feedback_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="assignmentupload",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignmentupload",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="courseenrollments",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="meetingdetails",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
