# Generated by Django 4.2.16 on 2025-02-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0043_alter_requestmeeting_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="email_alert",
            field=models.BooleanField(default=False),
        ),
    ]
