# Generated by Django 4.2.16 on 2025-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0044_userinfo_email_alert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestmeeting",
            name="req_description",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
    ]
