# Generated by Django 4.2.16 on 2025-03-08 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0045_alter_requestmeeting_req_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentupload",
            name="deadline",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
